{{- if eq .Values.workloadType "Frontend" }}
  {{- if and .Values.ingress.enabled .Values.service.enabled }}
    {{- $service_port := .Values.service.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bls-base-chart.fullname" . }}
  namespace: {{ include "bls-base-chart.namespace" . }}
  labels:
    app: {{ .Values.name }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bls-base-chart.fullname" $ }}
                port:
                  number: {{ $service_port }}
    {{- end }}
  ingressClassName: nginx
  {{- end }}
{{- end }}

