{{- if eq .Values.workloadType "job" }}
{{- $fullName := include "bls-base.fullname" . -}}
{{- $chart := include "bls-base.chart" . -}}
{{- $imageTag := .Values.image.tag | required ".Values.image.tag is required." -}}

---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Values.namespace }}
  generateName: {{ .Values.name }}-presync-job
  labels:
    app: {{ .Values.name }}  
  annotations:
    argocd.argoproj.io/hook: PreSync
    secrets.doppler.com/reload: "true"
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: {{ .Values.name }}-presync
        image: "{{ .Values.image.repository }}:{{ $imageTag }}"
        command: 
        - /bin/sh
        - -c
        - /var/www/html/.docker/php/pre-sync.sh
        envFrom:
          - secretRef:
              name: dopplersecret-{{ .Values.name }}
      restartPolicy: Never       
  backoffLimit: {{ .Values.backoffLimit }}