{{- if or (eq .Values.workloadType "Backend") (eq .Values.workloadType "Frontend") }}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bls-base-chart.fullname" . }}
  namespace: {{ include "bls-base-chart.namespace" . }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    app: {{ .Values.name }}
{{- end }}
{{- end }}
