{{- if .Values.ingress }}
  {{- if .Values.ingress.enabled }}
    {{- $ingressPaths := .Values.ingress.paths -}}
    {{- $name := .Values.name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/managed-by: helm
spec:
  ingressClassName: nginx
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- range $ingressPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}


