{{- if .Values.serviceAccount }}
  {{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/managed-by: helm
  annotations:
    {{- if .Values.service.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.service.roleArn }}
    {{- end }}
  {{- end }}
{{- end }}
