{{- if .Values.ingress }}
  {{- if .Values.ingress.enabled }}
    {{- $name := .Values.name }}
    {{- $service_port := .Values.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/managed-by: helm
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $service_port }}
    {{- end }}
  ingressClassName: nginx
  {{- end }}
{{- end }}
