environment: "dev"
namespace: "test"
name: "test"
project: "test"

serviceAccount:
  create: true
  name: "test"

service:
  enabled: true
  type: ClusterIP
  roleArn: arn:aws:iam::xxxx:role
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 443
      targetPort: 8443
      protocol: TCP

ingress:
  enabled: true
  hosts:
    - example.com
  paths:
    - path: /
      pathType: Prefix
      servicePort: 80


image:
  repository: "1242525:ecr" 
  tag: "242442"
  imagePullPolicy: IfNotPresent

deployment:
  enabled: true
  strategy: RollingUpdate
  replicaCount: 1
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    - name: https
      containerPort: 8443
      protocol: TCP
  resources:
    limits:
      cpu: 1.0
      memory: 100Mi
    requests:
      cpu: 1.0
      memory: 100Mi
  env: {}
  envFrom: {}
  command:
    - /bin/sh
    - -c
    - echo Hello World
  args: {}
     
  livenessProbe:
    path: /api/health
    port: 8080
    failureThreshold: 30
    periodSeconds: 10
    initialDelaySeconds: 0
  readinessProbe:
    path: /api/health
    port: 8080
    failureThreshold: 30
    periodSeconds: 10
    initialDelaySeconds: 0
  startupProbe:
    path: "/startup"
    port: 8080
    failureThreshold: 30
    periodSeconds: 10
    initialDelaySeconds: 0
  nodeSelector: {}
  tolerations: []
  affinity: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

doppler:
  required: true
  project: bikelease
  config: dev








