environment: ""
namespace: ""
name: "test"
project: "test"

image:
  repository: "1242525:ecr" 
  tag: "242442"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - example.com

resources:
  limits:
    cpu: 1.0
    memory: 100Mi
  requests:
    cpu: 1.0
    memory: 100Mi

deployment:
  enabled: true
  strategy: RollingUpdate

service:
  enabled: true
  port: 80
  roleArn: arn:aws:iam::xxxx:role
  
env: {}

envFrom: {}

securityContext: {}
podSecurityContext: {}

doppler:
  required: true
  project: bikelease
  config: dev

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  path: /api/health
  port: 8080
readinessProbe:
  path: /api/health
  port: 8080





