{{- define "shared-lib.serviceaccount" -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    {{- include "bls-base-chart.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.service.roleArn }}
{{- end }}
{{- end }}