environment: "int"
replicaCount: 1
name: "demo"
project: "demo"
image:
  repository: "your-repo/image"
  pullPolicy: IfNotPresent
  tag: "latest"

namespace: "demo"

serviceAccount:
  create: true
  annotations: {}
  name: "demo"

doppler:
  required: false
  project: "demo"
  config: int
  
service:
  enabled: true
  type: ClusterIP
  port: 8080
  protocol: TCP
  name: http
  roleArn: "demo"

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  tls: []
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

deployment:
  strategy: RollingUpdate
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

livenessProbe:
  path: /management/health
  port: 8080
  
readinessProbe:
  path: /management/health
  port: 8080

nodeSelector: {}
tolerations: []
affinity: {}

backoffLimit: 2

env:
  - name: SPRING_PROFILES_ACTIVE
    value: stg
  - name: JAVA_OPTS
    value: -Xmx200m -Xms200m -XX:MaxMetaspaceSize=96m -XX:ReservedCodeCacheSize=128m